CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'vendeur') NOT NULL DEFAULT 'vendeur',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sale_receipts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code_recu VARCHAR(20) NOT NULL UNIQUE,
  session_id VARCHAR(64) NOT NULL UNIQUE,
  vendeur_id INT UNSIGNED NOT NULL,
  date DATETIME NOT NULL,
  total_general DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  mode_paiement VARCHAR(50) NOT NULL,
  signature_vendeur VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sale_receipts_vendeur
    FOREIGN KEY (vendeur_id) REFERENCES users(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX sale_receipts_date_idx ON sale_receipts (date);

CREATE TABLE IF NOT EXISTS receipt_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  receipt_id INT UNSIGNED NOT NULL,
  nom_produit VARCHAR(255) NOT NULL,
  quantite INT UNSIGNED NOT NULL,
  prix_unitaire DECIMAL(12, 2) NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_receipt_items_receipt
    FOREIGN KEY (receipt_id) REFERENCES sale_receipts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS receipt_sequences (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  year INT UNSIGNED NOT NULL UNIQUE,
  current_value INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
